// Generated by tools/scanner.zig from protocols/cursor-shape-v1.xml. Do not edit.

const client = @import("../client.zig");
const wayland = @import("wayland.zig");

// wp_cursor_shape_manager_v1, version 2
pub const CursorShapeManagerV1 = opaque {
    pub const generated_version: u32 = 2;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "wp_cursor_shape_manager_v1",
        .version = 2,
        .method_count = 3,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "get_pointer", .signature = "no", .types = &[_]?*const client.Interface{ CursorShapeDeviceV1.interface, wayland.Pointer.interface } },
        .{ .name = "get_tablet_tool_v2", .signature = "no", .types = &[_]?*const client.Interface{ CursorShapeDeviceV1.interface, null } },
    };

    pub fn proxy(self: *CursorShapeManagerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub fn destroy(self: *CursorShapeManagerV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getPointer(self: *CursorShapeManagerV1, pointer: *wayland.Pointer) client.CreateError!*CursorShapeDeviceV1 {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(pointer) },
        };
        const created = self.proxy().marshalConstructor(1, CursorShapeDeviceV1.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    // get_tablet_tool_v2 is not generated: its `tablet_tool` argument names zwp_tablet_tool_v2, which is
    // not among the vendored protocols.
};

// wp_cursor_shape_device_v1, version 2
pub const CursorShapeDeviceV1 = opaque {
    pub const generated_version: u32 = 2;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "wp_cursor_shape_device_v1",
        .version = 2,
        .method_count = 2,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_shape", .signature = "uu", .types = &[_]?*const client.Interface{ null, null } },
    };

    pub fn proxy(self: *CursorShapeDeviceV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Shape = enum(u32) {
        default = 1,
        context_menu = 2,
        help = 3,
        pointer = 4,
        progress = 5,
        wait = 6,
        cell = 7,
        crosshair = 8,
        text = 9,
        vertical_text = 10,
        alias = 11,
        copy = 12,
        move = 13,
        no_drop = 14,
        not_allowed = 15,
        grab = 16,
        grabbing = 17,
        e_resize = 18,
        n_resize = 19,
        ne_resize = 20,
        nw_resize = 21,
        s_resize = 22,
        se_resize = 23,
        sw_resize = 24,
        w_resize = 25,
        ew_resize = 26,
        ns_resize = 27,
        nesw_resize = 28,
        nwse_resize = 29,
        col_resize = 30,
        row_resize = 31,
        all_scroll = 32,
        zoom_in = 33,
        zoom_out = 34,
        dnd_ask = 35,
        all_resize = 36,
        _,
    };

    pub const Error = enum(u32) {
        invalid_shape = 1,
        _,
    };

    pub fn destroy(self: *CursorShapeDeviceV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setShape(self: *CursorShapeDeviceV1, serial: u32, shape: Shape) void {
        var args = [_]client.Argument{
            .{ .u = serial },
            .{ .u = @intFromEnum(shape) },
        };
        self.proxy().marshal(1, &args);
    }
};
