// Generated by tools/scanner.zig from protocols/fractional-scale-v1.xml. Do not edit.

const client = @import("../client.zig");
const wayland = @import("wayland.zig");

// wp_fractional_scale_manager_v1, version 1
pub const FractionalScaleManagerV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "wp_fractional_scale_manager_v1",
        .version = 1,
        .method_count = 2,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "get_fractional_scale", .signature = "no", .types = &[_]?*const client.Interface{ FractionalScaleV1.interface, wayland.Surface.interface } },
    };

    pub fn proxy(self: *FractionalScaleManagerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        fractional_scale_exists = 0,
        _,
    };

    pub fn destroy(self: *FractionalScaleManagerV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getFractionalScale(self: *FractionalScaleManagerV1, surface: *wayland.Surface) client.CreateError!*FractionalScaleV1 {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
        };
        const created = self.proxy().marshalConstructor(1, FractionalScaleV1.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wp_fractional_scale_v1, version 1
pub const FractionalScaleV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "wp_fractional_scale_v1",
        .version = 1,
        .method_count = 1,
        .methods = &requests,
        .event_count = 1,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
    };

    const events = [_]client.Message{
        .{ .name = "preferred_scale", .signature = "u", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *FractionalScaleV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        preferred_scale: struct {
            scale: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .preferred_scale = .{
                .scale = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *FractionalScaleV1,
        comptime T: type,
        comptime handler: fn (*FractionalScaleV1, Event, T) void,
        data: T,
    ) void {
        client.addListener(FractionalScaleV1, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *FractionalScaleV1) void {
        self.proxy().marshalDestructor(0, null);
    }
};
