// Generated by tools/scanner.zig from protocols/pointer-constraints-unstable-v1.xml. Do not edit.

const client = @import("../client.zig");
const wayland = @import("wayland.zig");

// zwp_pointer_constraints_v1, version 1
pub const PointerConstraintsV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zwp_pointer_constraints_v1",
        .version = 1,
        .method_count = 3,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "lock_pointer", .signature = "noo?ou", .types = &[_]?*const client.Interface{ LockedPointerV1.interface, wayland.Surface.interface, wayland.Pointer.interface, wayland.Region.interface, null } },
        .{ .name = "confine_pointer", .signature = "noo?ou", .types = &[_]?*const client.Interface{ ConfinedPointerV1.interface, wayland.Surface.interface, wayland.Pointer.interface, wayland.Region.interface, null } },
    };

    pub fn proxy(self: *PointerConstraintsV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        already_constrained = 1,
        _,
    };

    pub const Lifetime = enum(u32) {
        oneshot = 1,
        persistent = 2,
        _,
    };

    pub fn destroy(self: *PointerConstraintsV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn lockPointer(self: *PointerConstraintsV1, surface: *wayland.Surface, pointer: *wayland.Pointer, region: ?*wayland.Region, lifetime: Lifetime) client.CreateError!*LockedPointerV1 {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
            .{ .o = @ptrCast(pointer) },
            .{ .o = @ptrCast(region) },
            .{ .u = @intFromEnum(lifetime) },
        };
        const created = self.proxy().marshalConstructor(1, LockedPointerV1.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn confinePointer(self: *PointerConstraintsV1, surface: *wayland.Surface, pointer: *wayland.Pointer, region: ?*wayland.Region, lifetime: Lifetime) client.CreateError!*ConfinedPointerV1 {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
            .{ .o = @ptrCast(pointer) },
            .{ .o = @ptrCast(region) },
            .{ .u = @intFromEnum(lifetime) },
        };
        const created = self.proxy().marshalConstructor(2, ConfinedPointerV1.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// zwp_locked_pointer_v1, version 1
pub const LockedPointerV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zwp_locked_pointer_v1",
        .version = 1,
        .method_count = 3,
        .methods = &requests,
        .event_count = 2,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_cursor_position_hint", .signature = "ff", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "set_region", .signature = "?o", .types = &[_]?*const client.Interface{wayland.Region.interface} },
    };

    const events = [_]client.Message{
        .{ .name = "locked", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "unlocked", .signature = "", .types = &[_]?*const client.Interface{} },
    };

    pub fn proxy(self: *LockedPointerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        locked,
        unlocked,
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, _: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .locked,
            1 => .unlocked,
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *LockedPointerV1,
        comptime T: type,
        comptime handler: fn (*LockedPointerV1, Event, T) void,
        data: T,
    ) void {
        client.addListener(LockedPointerV1, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *LockedPointerV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setCursorPositionHint(self: *LockedPointerV1, surface_x: client.Fixed, surface_y: client.Fixed) void {
        var args = [_]client.Argument{
            .{ .f = surface_x },
            .{ .f = surface_y },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn setRegion(self: *LockedPointerV1, region: ?*wayland.Region) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(region) },
        };
        self.proxy().marshal(2, &args);
    }
};

// zwp_confined_pointer_v1, version 1
pub const ConfinedPointerV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zwp_confined_pointer_v1",
        .version = 1,
        .method_count = 2,
        .methods = &requests,
        .event_count = 2,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_region", .signature = "?o", .types = &[_]?*const client.Interface{wayland.Region.interface} },
    };

    const events = [_]client.Message{
        .{ .name = "confined", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "unconfined", .signature = "", .types = &[_]?*const client.Interface{} },
    };

    pub fn proxy(self: *ConfinedPointerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        confined,
        unconfined,
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, _: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .confined,
            1 => .unconfined,
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *ConfinedPointerV1,
        comptime T: type,
        comptime handler: fn (*ConfinedPointerV1, Event, T) void,
        data: T,
    ) void {
        client.addListener(ConfinedPointerV1, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *ConfinedPointerV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setRegion(self: *ConfinedPointerV1, region: ?*wayland.Region) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(region) },
        };
        self.proxy().marshal(1, &args);
    }
};
