// Generated by tools/scanner.zig from protocols/relative-pointer-unstable-v1.xml. Do not edit.

const client = @import("../client.zig");
const wayland = @import("wayland.zig");

// zwp_relative_pointer_manager_v1, version 1
pub const RelativePointerManagerV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zwp_relative_pointer_manager_v1",
        .version = 1,
        .method_count = 2,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "get_relative_pointer", .signature = "no", .types = &[_]?*const client.Interface{ RelativePointerV1.interface, wayland.Pointer.interface } },
    };

    pub fn proxy(self: *RelativePointerManagerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub fn destroy(self: *RelativePointerManagerV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getRelativePointer(self: *RelativePointerManagerV1, pointer: *wayland.Pointer) client.CreateError!*RelativePointerV1 {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(pointer) },
        };
        const created = self.proxy().marshalConstructor(1, RelativePointerV1.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// zwp_relative_pointer_v1, version 1
pub const RelativePointerV1 = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zwp_relative_pointer_v1",
        .version = 1,
        .method_count = 1,
        .methods = &requests,
        .event_count = 1,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
    };

    const events = [_]client.Message{
        .{ .name = "relative_motion", .signature = "uuffff", .types = &[_]?*const client.Interface{ null, null, null, null, null, null } },
    };

    pub fn proxy(self: *RelativePointerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        relative_motion: struct {
            utime_hi: u32,
            utime_lo: u32,
            dx: client.Fixed,
            dy: client.Fixed,
            dx_unaccel: client.Fixed,
            dy_unaccel: client.Fixed,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .relative_motion = .{
                .utime_hi = args[0].u,
                .utime_lo = args[1].u,
                .dx = args[2].f,
                .dy = args[3].f,
                .dx_unaccel = args[4].f,
                .dy_unaccel = args[5].f,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *RelativePointerV1,
        comptime T: type,
        comptime handler: fn (*RelativePointerV1, Event, T) void,
        data: T,
    ) void {
        client.addListener(RelativePointerV1, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *RelativePointerV1) void {
        self.proxy().marshalDestructor(0, null);
    }
};
