// Generated by tools/scanner.zig from protocols/viewporter.xml. Do not edit.

const client = @import("../client.zig");
const wayland = @import("wayland.zig");

// wp_viewporter, version 1
pub const Viewporter = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "wp_viewporter",
        .version = 1,
        .method_count = 2,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "get_viewport", .signature = "no", .types = &[_]?*const client.Interface{ Viewport.interface, wayland.Surface.interface } },
    };

    pub fn proxy(self: *Viewporter) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        viewport_exists = 0,
        _,
    };

    pub fn destroy(self: *Viewporter) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getViewport(self: *Viewporter, surface: *wayland.Surface) client.CreateError!*Viewport {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
        };
        const created = self.proxy().marshalConstructor(1, Viewport.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wp_viewport, version 1
pub const Viewport = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "wp_viewport",
        .version = 1,
        .method_count = 3,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_source", .signature = "ffff", .types = &[_]?*const client.Interface{ null, null, null, null } },
        .{ .name = "set_destination", .signature = "ii", .types = &[_]?*const client.Interface{ null, null } },
    };

    pub fn proxy(self: *Viewport) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        bad_value = 0,
        bad_size = 1,
        out_of_buffer = 2,
        no_surface = 3,
        _,
    };

    pub fn destroy(self: *Viewport) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setSource(self: *Viewport, x: client.Fixed, y: client.Fixed, width: client.Fixed, height: client.Fixed) void {
        var args = [_]client.Argument{
            .{ .f = x },
            .{ .f = y },
            .{ .f = width },
            .{ .f = height },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn setDestination(self: *Viewport, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(2, &args);
    }
};
