// Generated by tools/scanner.zig from protocols/wayland.xml. Do not edit.

const client = @import("../client.zig");

// Defined by libwayland-client rather than here: the core protocol's
// tables ship inside the library, and a second copy would not compare
// equal to the one Vulkan's WSI and libwayland itself already use.
extern const wl_display_interface: client.Interface;
extern const wl_registry_interface: client.Interface;
extern const wl_callback_interface: client.Interface;
extern const wl_compositor_interface: client.Interface;
extern const wl_shm_pool_interface: client.Interface;
extern const wl_shm_interface: client.Interface;
extern const wl_buffer_interface: client.Interface;
extern const wl_data_offer_interface: client.Interface;
extern const wl_data_source_interface: client.Interface;
extern const wl_data_device_interface: client.Interface;
extern const wl_data_device_manager_interface: client.Interface;
extern const wl_shell_interface: client.Interface;
extern const wl_shell_surface_interface: client.Interface;
extern const wl_surface_interface: client.Interface;
extern const wl_seat_interface: client.Interface;
extern const wl_pointer_interface: client.Interface;
extern const wl_keyboard_interface: client.Interface;
extern const wl_touch_interface: client.Interface;
extern const wl_output_interface: client.Interface;
extern const wl_region_interface: client.Interface;
extern const wl_subcompositor_interface: client.Interface;
extern const wl_subsurface_interface: client.Interface;
extern const wl_fixes_interface: client.Interface;

// wl_display, version 1
pub const Display = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_display_interface;

    pub fn proxy(self: *Display) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_object = 0,
        invalid_method = 1,
        no_memory = 2,
        implementation = 3,
        _,
    };

    pub const Event = union(enum) {
        @"error": struct {
            object_id: ?*client.Proxy,
            code: u32,
            message: [*:0]const u8,
        },
        delete_id: struct {
            id: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .@"error" = .{
                .object_id = @ptrCast(args[0].o),
                .code = args[1].u,
                .message = args[2].s.?,
            } },
            1 => .{ .delete_id = .{
                .id = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Display,
        comptime T: type,
        comptime handler: fn (*Display, Event, T) void,
        data: T,
    ) void {
        client.addListener(Display, Event, decodeEvent, T, handler, self, data);
    }

    pub fn sync(self: *Display) client.CreateError!*Callback {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(0, Callback.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn getRegistry(self: *Display) client.CreateError!*Registry {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(1, Registry.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wl_registry, version 1
pub const Registry = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_registry_interface;

    pub fn proxy(self: *Registry) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        global: struct {
            name: u32,
            interface: [*:0]const u8,
            version: u32,
        },
        global_remove: struct {
            name: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .global = .{
                .name = args[0].u,
                .interface = args[1].s.?,
                .version = args[2].u,
            } },
            1 => .{ .global_remove = .{
                .name = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Registry,
        comptime T: type,
        comptime handler: fn (*Registry, Event, T) void,
        data: T,
    ) void {
        client.addListener(Registry, Event, decodeEvent, T, handler, self, data);
    }

    pub fn bind(self: *Registry, name: u32, comptime T: type, version: u32) client.CreateError!*T {
        var args = [_]client.Argument{
            .{ .u = name },
            .{ .s = T.interface.name },
            .{ .u = version },
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructorVersioned(0, T.interface, version, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wl_callback, version 1
pub const Callback = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_callback_interface;

    pub fn proxy(self: *Callback) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        done: struct {
            callback_data: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .done = .{
                .callback_data = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Callback,
        comptime T: type,
        comptime handler: fn (*Callback, Event, T) void,
        data: T,
    ) void {
        client.addListener(Callback, Event, decodeEvent, T, handler, self, data);
    }
};

// wl_compositor, version 7
pub const Compositor = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &wl_compositor_interface;

    pub fn proxy(self: *Compositor) *client.Proxy {
        return @ptrCast(self);
    }

    pub const since = struct {
        pub const release: u32 = 7;
    };

    pub fn createSurface(self: *Compositor) client.CreateError!*Surface {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(0, Surface.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn createRegion(self: *Compositor) client.CreateError!*Region {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(1, Region.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    // since version 7
    pub fn release(self: *Compositor) void {
        self.proxy().marshalDestructor(2, null);
    }
};

// wl_shm_pool, version 3
pub const ShmPool = opaque {
    pub const generated_version: u32 = 3;

    pub const interface: *const client.Interface = &wl_shm_pool_interface;

    pub fn proxy(self: *ShmPool) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_format = 0,
        invalid_stride = 1,
        _,
    };

    pub fn createBuffer(self: *ShmPool, offset: i32, width: i32, height: i32, stride: i32, format: Shm.Format) client.CreateError!*Buffer {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .i = offset },
            .{ .i = width },
            .{ .i = height },
            .{ .i = stride },
            .{ .u = @intFromEnum(format) },
        };
        const created = self.proxy().marshalConstructor(0, Buffer.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn destroy(self: *ShmPool) void {
        self.proxy().marshalDestructor(1, null);
    }

    pub fn resize(self: *ShmPool, size: i32) void {
        var args = [_]client.Argument{
            .{ .i = size },
        };
        self.proxy().marshal(2, &args);
    }
};

// wl_shm, version 3
pub const Shm = opaque {
    pub const generated_version: u32 = 3;

    pub const interface: *const client.Interface = &wl_shm_interface;

    pub fn proxy(self: *Shm) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_format = 0,
        invalid_stride = 1,
        invalid_fd = 2,
        _,
    };

    pub const Format = enum(u32) {
        argb8888 = 0,
        xrgb8888 = 1,
        c8 = 538982467,
        rgb332 = 943867730,
        bgr233 = 944916290,
        xrgb4444 = 842093144,
        xbgr4444 = 842089048,
        rgbx4444 = 842094674,
        bgrx4444 = 842094658,
        argb4444 = 842093121,
        abgr4444 = 842089025,
        rgba4444 = 842088786,
        bgra4444 = 842088770,
        xrgb1555 = 892424792,
        xbgr1555 = 892420696,
        rgbx5551 = 892426322,
        bgrx5551 = 892426306,
        argb1555 = 892424769,
        abgr1555 = 892420673,
        rgba5551 = 892420434,
        bgra5551 = 892420418,
        rgb565 = 909199186,
        bgr565 = 909199170,
        rgb888 = 875710290,
        bgr888 = 875710274,
        xbgr8888 = 875709016,
        rgbx8888 = 875714642,
        bgrx8888 = 875714626,
        abgr8888 = 875708993,
        rgba8888 = 875708754,
        bgra8888 = 875708738,
        xrgb2101010 = 808669784,
        xbgr2101010 = 808665688,
        rgbx1010102 = 808671314,
        bgrx1010102 = 808671298,
        argb2101010 = 808669761,
        abgr2101010 = 808665665,
        rgba1010102 = 808665426,
        bgra1010102 = 808665410,
        yuyv = 1448695129,
        yvyu = 1431918169,
        uyvy = 1498831189,
        vyuy = 1498765654,
        ayuv = 1448433985,
        nv12 = 842094158,
        nv21 = 825382478,
        nv16 = 909203022,
        nv61 = 825644622,
        yuv410 = 961959257,
        yvu410 = 961893977,
        yuv411 = 825316697,
        yvu411 = 825316953,
        yuv420 = 842093913,
        yvu420 = 842094169,
        yuv422 = 909202777,
        yvu422 = 909203033,
        yuv444 = 875713881,
        yvu444 = 875714137,
        r8 = 538982482,
        r16 = 540422482,
        rg88 = 943212370,
        gr88 = 943215175,
        rg1616 = 842221394,
        gr1616 = 842224199,
        xrgb16161616f = 1211388504,
        xbgr16161616f = 1211384408,
        argb16161616f = 1211388481,
        abgr16161616f = 1211384385,
        xyuv8888 = 1448434008,
        vuy888 = 875713878,
        vuy101010 = 808670550,
        y210 = 808530521,
        y212 = 842084953,
        y216 = 909193817,
        y410 = 808531033,
        y412 = 842085465,
        y416 = 909194329,
        xvyu2101010 = 808670808,
        xvyu12_16161616 = 909334104,
        xvyu16161616 = 942954072,
        y0l0 = 810299481,
        x0l0 = 810299480,
        y0l2 = 843853913,
        x0l2 = 843853912,
        yuv420_8bit = 942691673,
        yuv420_10bit = 808539481,
        xrgb8888_a8 = 943805016,
        xbgr8888_a8 = 943800920,
        rgbx8888_a8 = 943806546,
        bgrx8888_a8 = 943806530,
        rgb888_a8 = 943798354,
        bgr888_a8 = 943798338,
        rgb565_a8 = 943797586,
        bgr565_a8 = 943797570,
        nv24 = 875714126,
        nv42 = 842290766,
        p210 = 808530512,
        p010 = 808530000,
        p012 = 842084432,
        p016 = 909193296,
        axbxgxrx106106106106 = 808534593,
        nv15 = 892425806,
        q410 = 808531025,
        q401 = 825242705,
        xrgb16161616 = 942953048,
        xbgr16161616 = 942948952,
        argb16161616 = 942953025,
        abgr16161616 = 942948929,
        c1 = 538980675,
        c2 = 538980931,
        c4 = 538981443,
        d1 = 538980676,
        d2 = 538980932,
        d4 = 538981444,
        d8 = 538982468,
        r1 = 538980690,
        r2 = 538980946,
        r4 = 538981458,
        r10 = 540029266,
        r12 = 540160338,
        avuy8888 = 1498764865,
        xvuy8888 = 1498764888,
        p030 = 808661072,
        rgb161616 = 942950226,
        bgr161616 = 942950210,
        r16f = 1210064978,
        gr1616f = 1210077767,
        bgr161616f = 1213351746,
        r32f = 1176510546,
        gr3232f = 1176523335,
        bgr323232f = 1179797314,
        abgr32323232f = 1178092097,
        nv20 = 808605262,
        nv30 = 808670798,
        s010 = 808530003,
        s210 = 808530515,
        s410 = 808531027,
        s012 = 842084435,
        s212 = 842084947,
        s412 = 842085459,
        s016 = 909193299,
        s216 = 909193811,
        s416 = 909194323,
        xvuy2101010 = 808671576,
        p230 = 808661584,
        t430 = 808662100,
        y8 = 1497715271,
        xyyy2101010 = 876695641,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 2;
    };

    pub const Event = union(enum) {
        format: struct {
            format: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .format = .{
                .format = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Shm,
        comptime T: type,
        comptime handler: fn (*Shm, Event, T) void,
        data: T,
    ) void {
        client.addListener(Shm, Event, decodeEvent, T, handler, self, data);
    }

    pub fn createPool(self: *Shm, fd: i32, size: i32) client.CreateError!*ShmPool {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .h = fd },
            .{ .i = size },
        };
        const created = self.proxy().marshalConstructor(0, ShmPool.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    // since version 2
    pub fn release(self: *Shm) void {
        self.proxy().marshalDestructor(1, null);
    }
};

// wl_buffer, version 1
pub const Buffer = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_buffer_interface;

    pub fn proxy(self: *Buffer) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Event = union(enum) {
        release,
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, _: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .release,
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Buffer,
        comptime T: type,
        comptime handler: fn (*Buffer, Event, T) void,
        data: T,
    ) void {
        client.addListener(Buffer, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *Buffer) void {
        self.proxy().marshalDestructor(0, null);
    }
};

// wl_data_offer, version 4
pub const DataOffer = opaque {
    pub const generated_version: u32 = 4;

    pub const interface: *const client.Interface = &wl_data_offer_interface;

    pub fn proxy(self: *DataOffer) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_finish = 0,
        invalid_action_mask = 1,
        invalid_action = 2,
        invalid_offer = 3,
        _,
    };

    pub const since = struct {
        pub const finish: u32 = 3;
        pub const setActions: u32 = 3;
    };

    pub const Event = union(enum) {
        offer: struct {
            mime_type: [*:0]const u8,
        },
        source_actions: struct {
            source_actions: u32,
        },
        action: struct {
            dnd_action: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .offer = .{
                .mime_type = args[0].s.?,
            } },
            1 => .{ .source_actions = .{
                .source_actions = args[0].u,
            } },
            2 => .{ .action = .{
                .dnd_action = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *DataOffer,
        comptime T: type,
        comptime handler: fn (*DataOffer, Event, T) void,
        data: T,
    ) void {
        client.addListener(DataOffer, Event, decodeEvent, T, handler, self, data);
    }

    pub fn accept(self: *DataOffer, serial: u32, mime_type: ?[*:0]const u8) void {
        var args = [_]client.Argument{
            .{ .u = serial },
            .{ .s = mime_type },
        };
        self.proxy().marshal(0, &args);
    }

    pub fn receive(self: *DataOffer, mime_type: [*:0]const u8, fd: i32) void {
        var args = [_]client.Argument{
            .{ .s = mime_type },
            .{ .h = fd },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn destroy(self: *DataOffer) void {
        self.proxy().marshalDestructor(2, null);
    }

    // since version 3
    pub fn finish(self: *DataOffer) void {
        self.proxy().marshal(3, null);
    }

    // since version 3
    pub fn setActions(self: *DataOffer, dnd_actions: DataDeviceManager.DndAction, preferred_action: DataDeviceManager.DndAction) void {
        var args = [_]client.Argument{
            .{ .u = @intFromEnum(dnd_actions) },
            .{ .u = @intFromEnum(preferred_action) },
        };
        self.proxy().marshal(4, &args);
    }
};

// wl_data_source, version 4
pub const DataSource = opaque {
    pub const generated_version: u32 = 4;

    pub const interface: *const client.Interface = &wl_data_source_interface;

    pub fn proxy(self: *DataSource) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_action_mask = 0,
        invalid_source = 1,
        _,
    };

    pub const since = struct {
        pub const setActions: u32 = 3;
    };

    pub const Event = union(enum) {
        target: struct {
            mime_type: ?[*:0]const u8,
        },
        send: struct {
            mime_type: [*:0]const u8,
            fd: i32,
        },
        cancelled,
        dnd_drop_performed,
        dnd_finished,
        action: struct {
            dnd_action: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .target = .{
                .mime_type = args[0].s,
            } },
            1 => .{ .send = .{
                .mime_type = args[0].s.?,
                .fd = args[1].h,
            } },
            2 => .cancelled,
            3 => .dnd_drop_performed,
            4 => .dnd_finished,
            5 => .{ .action = .{
                .dnd_action = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *DataSource,
        comptime T: type,
        comptime handler: fn (*DataSource, Event, T) void,
        data: T,
    ) void {
        client.addListener(DataSource, Event, decodeEvent, T, handler, self, data);
    }

    pub fn offer(self: *DataSource, mime_type: [*:0]const u8) void {
        var args = [_]client.Argument{
            .{ .s = mime_type },
        };
        self.proxy().marshal(0, &args);
    }

    pub fn destroy(self: *DataSource) void {
        self.proxy().marshalDestructor(1, null);
    }

    // since version 3
    pub fn setActions(self: *DataSource, dnd_actions: DataDeviceManager.DndAction) void {
        var args = [_]client.Argument{
            .{ .u = @intFromEnum(dnd_actions) },
        };
        self.proxy().marshal(2, &args);
    }
};

// wl_data_device, version 4
pub const DataDevice = opaque {
    pub const generated_version: u32 = 4;

    pub const interface: *const client.Interface = &wl_data_device_interface;

    pub fn proxy(self: *DataDevice) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        role = 0,
        used_source = 1,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 2;
    };

    pub const Event = union(enum) {
        data_offer: struct {
            id: *DataOffer,
        },
        enter: struct {
            serial: u32,
            surface: ?*Surface,
            x: client.Fixed,
            y: client.Fixed,
            id: ?*DataOffer,
        },
        leave,
        motion: struct {
            time: u32,
            x: client.Fixed,
            y: client.Fixed,
        },
        drop,
        selection: struct {
            id: ?*DataOffer,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .data_offer = .{
                .id = @ptrCast(args[0].o.?),
            } },
            1 => .{ .enter = .{
                .serial = args[0].u,
                .surface = @ptrCast(args[1].o),
                .x = args[2].f,
                .y = args[3].f,
                .id = @ptrCast(args[4].o),
            } },
            2 => .leave,
            3 => .{ .motion = .{
                .time = args[0].u,
                .x = args[1].f,
                .y = args[2].f,
            } },
            4 => .drop,
            5 => .{ .selection = .{
                .id = @ptrCast(args[0].o),
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *DataDevice,
        comptime T: type,
        comptime handler: fn (*DataDevice, Event, T) void,
        data: T,
    ) void {
        client.addListener(DataDevice, Event, decodeEvent, T, handler, self, data);
    }

    pub fn startDrag(self: *DataDevice, source: ?*DataSource, origin: *Surface, icon: ?*Surface, serial: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(source) },
            .{ .o = @ptrCast(origin) },
            .{ .o = @ptrCast(icon) },
            .{ .u = serial },
        };
        self.proxy().marshal(0, &args);
    }

    pub fn setSelection(self: *DataDevice, source: ?*DataSource, serial: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(source) },
            .{ .u = serial },
        };
        self.proxy().marshal(1, &args);
    }

    // since version 2
    pub fn release(self: *DataDevice) void {
        self.proxy().marshalDestructor(2, null);
    }
};

// wl_data_device_manager, version 4
pub const DataDeviceManager = opaque {
    pub const generated_version: u32 = 4;

    pub const interface: *const client.Interface = &wl_data_device_manager_interface;

    pub fn proxy(self: *DataDeviceManager) *client.Proxy {
        return @ptrCast(self);
    }

    pub const DndAction = enum(u32) {
        none = 0,
        copy = 1,
        move = 2,
        ask = 4,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 4;
    };

    pub fn createDataSource(self: *DataDeviceManager) client.CreateError!*DataSource {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(0, DataSource.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn getDataDevice(self: *DataDeviceManager, seat: *Seat) client.CreateError!*DataDevice {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(seat) },
        };
        const created = self.proxy().marshalConstructor(1, DataDevice.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    // since version 4
    pub fn release(self: *DataDeviceManager) void {
        self.proxy().marshalDestructor(2, null);
    }
};

// wl_shell, version 1
pub const Shell = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_shell_interface;

    pub fn proxy(self: *Shell) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        role = 0,
        _,
    };

    pub fn getShellSurface(self: *Shell, surface: *Surface) client.CreateError!*ShellSurface {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
        };
        const created = self.proxy().marshalConstructor(0, ShellSurface.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wl_shell_surface, version 1
pub const ShellSurface = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_shell_surface_interface;

    pub fn proxy(self: *ShellSurface) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Resize = enum(u32) {
        none = 0,
        top = 1,
        bottom = 2,
        left = 4,
        top_left = 5,
        bottom_left = 6,
        right = 8,
        top_right = 9,
        bottom_right = 10,
        _,
    };

    pub const Transient = enum(u32) {
        inactive = 1,
        _,
    };

    pub const FullscreenMethod = enum(u32) {
        default = 0,
        scale = 1,
        driver = 2,
        fill = 3,
        _,
    };

    pub const Event = union(enum) {
        ping: struct {
            serial: u32,
        },
        configure: struct {
            edges: u32,
            width: i32,
            height: i32,
        },
        popup_done,
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .ping = .{
                .serial = args[0].u,
            } },
            1 => .{ .configure = .{
                .edges = args[0].u,
                .width = args[1].i,
                .height = args[2].i,
            } },
            2 => .popup_done,
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *ShellSurface,
        comptime T: type,
        comptime handler: fn (*ShellSurface, Event, T) void,
        data: T,
    ) void {
        client.addListener(ShellSurface, Event, decodeEvent, T, handler, self, data);
    }

    pub fn pong(self: *ShellSurface, serial: u32) void {
        var args = [_]client.Argument{
            .{ .u = serial },
        };
        self.proxy().marshal(0, &args);
    }

    pub fn move(self: *ShellSurface, seat: *Seat, serial: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn resize(self: *ShellSurface, seat: *Seat, serial: u32, edges: Resize) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
            .{ .u = @intFromEnum(edges) },
        };
        self.proxy().marshal(2, &args);
    }

    pub fn setToplevel(self: *ShellSurface) void {
        self.proxy().marshal(3, null);
    }

    pub fn setTransient(self: *ShellSurface, parent: *Surface, x: i32, y: i32, flags: Transient) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(parent) },
            .{ .i = x },
            .{ .i = y },
            .{ .u = @intFromEnum(flags) },
        };
        self.proxy().marshal(4, &args);
    }

    pub fn setFullscreen(self: *ShellSurface, method: FullscreenMethod, framerate: u32, output: ?*Output) void {
        var args = [_]client.Argument{
            .{ .u = @intFromEnum(method) },
            .{ .u = framerate },
            .{ .o = @ptrCast(output) },
        };
        self.proxy().marshal(5, &args);
    }

    pub fn setPopup(self: *ShellSurface, seat: *Seat, serial: u32, parent: *Surface, x: i32, y: i32, flags: Transient) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
            .{ .o = @ptrCast(parent) },
            .{ .i = x },
            .{ .i = y },
            .{ .u = @intFromEnum(flags) },
        };
        self.proxy().marshal(6, &args);
    }

    pub fn setMaximized(self: *ShellSurface, output: ?*Output) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(output) },
        };
        self.proxy().marshal(7, &args);
    }

    pub fn setTitle(self: *ShellSurface, title: [*:0]const u8) void {
        var args = [_]client.Argument{
            .{ .s = title },
        };
        self.proxy().marshal(8, &args);
    }

    pub fn setClass(self: *ShellSurface, class_: [*:0]const u8) void {
        var args = [_]client.Argument{
            .{ .s = class_ },
        };
        self.proxy().marshal(9, &args);
    }
};

// wl_surface, version 7
pub const Surface = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &wl_surface_interface;

    pub fn proxy(self: *Surface) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_scale = 0,
        invalid_transform = 1,
        invalid_size = 2,
        invalid_offset = 3,
        defunct_role_object = 4,
        no_buffer = 5,
        _,
    };

    pub const since = struct {
        pub const setBufferTransform: u32 = 2;
        pub const setBufferScale: u32 = 3;
        pub const damageBuffer: u32 = 4;
        pub const offset: u32 = 5;
        pub const getRelease: u32 = 7;
    };

    pub const Event = union(enum) {
        enter: struct {
            output: ?*Output,
        },
        leave: struct {
            output: ?*Output,
        },
        preferred_buffer_scale: struct {
            factor: i32,
        },
        preferred_buffer_transform: struct {
            transform: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .enter = .{
                .output = @ptrCast(args[0].o),
            } },
            1 => .{ .leave = .{
                .output = @ptrCast(args[0].o),
            } },
            2 => .{ .preferred_buffer_scale = .{
                .factor = args[0].i,
            } },
            3 => .{ .preferred_buffer_transform = .{
                .transform = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Surface,
        comptime T: type,
        comptime handler: fn (*Surface, Event, T) void,
        data: T,
    ) void {
        client.addListener(Surface, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *Surface) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn attach(self: *Surface, buffer: ?*Buffer, x: i32, y: i32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(buffer) },
            .{ .i = x },
            .{ .i = y },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn damage(self: *Surface, x: i32, y: i32, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(2, &args);
    }

    pub fn frame(self: *Surface) client.CreateError!*Callback {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(3, Callback.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn setOpaqueRegion(self: *Surface, region: ?*Region) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(region) },
        };
        self.proxy().marshal(4, &args);
    }

    pub fn setInputRegion(self: *Surface, region: ?*Region) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(region) },
        };
        self.proxy().marshal(5, &args);
    }

    pub fn commit(self: *Surface) void {
        self.proxy().marshal(6, null);
    }

    // since version 2
    pub fn setBufferTransform(self: *Surface, transform: Output.Transform) void {
        var args = [_]client.Argument{
            .{ .i = @intCast(@intFromEnum(transform)) },
        };
        self.proxy().marshal(7, &args);
    }

    // since version 3
    pub fn setBufferScale(self: *Surface, scale: i32) void {
        var args = [_]client.Argument{
            .{ .i = scale },
        };
        self.proxy().marshal(8, &args);
    }

    // since version 4
    pub fn damageBuffer(self: *Surface, x: i32, y: i32, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(9, &args);
    }

    // since version 5
    pub fn offset(self: *Surface, x: i32, y: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
        };
        self.proxy().marshal(10, &args);
    }

    // since version 7
    pub fn getRelease(self: *Surface) client.CreateError!*Callback {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(11, Callback.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wl_seat, version 11
pub const Seat = opaque {
    pub const generated_version: u32 = 11;

    pub const interface: *const client.Interface = &wl_seat_interface;

    pub fn proxy(self: *Seat) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Capability = enum(u32) {
        pointer = 1,
        keyboard = 2,
        touch = 4,
        _,
    };

    pub const Error = enum(u32) {
        missing_capability = 0,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 5;
    };

    pub const Event = union(enum) {
        capabilities: struct {
            capabilities: u32,
        },
        name: struct {
            name: [*:0]const u8,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .capabilities = .{
                .capabilities = args[0].u,
            } },
            1 => .{ .name = .{
                .name = args[0].s.?,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Seat,
        comptime T: type,
        comptime handler: fn (*Seat, Event, T) void,
        data: T,
    ) void {
        client.addListener(Seat, Event, decodeEvent, T, handler, self, data);
    }

    pub fn getPointer(self: *Seat) client.CreateError!*Pointer {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(0, Pointer.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn getKeyboard(self: *Seat) client.CreateError!*Keyboard {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(1, Keyboard.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn getTouch(self: *Seat) client.CreateError!*Touch {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(2, Touch.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    // since version 5
    pub fn release(self: *Seat) void {
        self.proxy().marshalDestructor(3, null);
    }
};

// wl_pointer, version 11
pub const Pointer = opaque {
    pub const generated_version: u32 = 11;

    pub const interface: *const client.Interface = &wl_pointer_interface;

    pub fn proxy(self: *Pointer) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        role = 0,
        _,
    };

    pub const ButtonState = enum(u32) {
        released = 0,
        pressed = 1,
        _,
    };

    pub const Axis = enum(u32) {
        vertical_scroll = 0,
        horizontal_scroll = 1,
        _,
    };

    pub const AxisSource = enum(u32) {
        wheel = 0,
        finger = 1,
        continuous = 2,
        wheel_tilt = 3,
        _,
    };

    pub const AxisRelativeDirection = enum(u32) {
        identical = 0,
        inverted = 1,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 3;
    };

    pub const Event = union(enum) {
        enter: struct {
            serial: u32,
            surface: ?*Surface,
            surface_x: client.Fixed,
            surface_y: client.Fixed,
        },
        leave: struct {
            serial: u32,
            surface: ?*Surface,
        },
        motion: struct {
            time: u32,
            surface_x: client.Fixed,
            surface_y: client.Fixed,
        },
        button: struct {
            serial: u32,
            time: u32,
            button: u32,
            state: u32,
        },
        axis: struct {
            time: u32,
            axis: u32,
            value: client.Fixed,
        },
        frame,
        axis_source: struct {
            axis_source: u32,
        },
        axis_stop: struct {
            time: u32,
            axis: u32,
        },
        axis_discrete: struct {
            axis: u32,
            discrete: i32,
        },
        axis_value120: struct {
            axis: u32,
            value120: i32,
        },
        axis_relative_direction: struct {
            axis: u32,
            direction: u32,
        },
        warp: struct {
            surface_x: client.Fixed,
            surface_y: client.Fixed,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .enter = .{
                .serial = args[0].u,
                .surface = @ptrCast(args[1].o),
                .surface_x = args[2].f,
                .surface_y = args[3].f,
            } },
            1 => .{ .leave = .{
                .serial = args[0].u,
                .surface = @ptrCast(args[1].o),
            } },
            2 => .{ .motion = .{
                .time = args[0].u,
                .surface_x = args[1].f,
                .surface_y = args[2].f,
            } },
            3 => .{ .button = .{
                .serial = args[0].u,
                .time = args[1].u,
                .button = args[2].u,
                .state = args[3].u,
            } },
            4 => .{ .axis = .{
                .time = args[0].u,
                .axis = args[1].u,
                .value = args[2].f,
            } },
            5 => .frame,
            6 => .{ .axis_source = .{
                .axis_source = args[0].u,
            } },
            7 => .{ .axis_stop = .{
                .time = args[0].u,
                .axis = args[1].u,
            } },
            8 => .{ .axis_discrete = .{
                .axis = args[0].u,
                .discrete = args[1].i,
            } },
            9 => .{ .axis_value120 = .{
                .axis = args[0].u,
                .value120 = args[1].i,
            } },
            10 => .{ .axis_relative_direction = .{
                .axis = args[0].u,
                .direction = args[1].u,
            } },
            11 => .{ .warp = .{
                .surface_x = args[0].f,
                .surface_y = args[1].f,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Pointer,
        comptime T: type,
        comptime handler: fn (*Pointer, Event, T) void,
        data: T,
    ) void {
        client.addListener(Pointer, Event, decodeEvent, T, handler, self, data);
    }

    pub fn setCursor(self: *Pointer, serial: u32, surface: ?*Surface, hotspot_x: i32, hotspot_y: i32) void {
        var args = [_]client.Argument{
            .{ .u = serial },
            .{ .o = @ptrCast(surface) },
            .{ .i = hotspot_x },
            .{ .i = hotspot_y },
        };
        self.proxy().marshal(0, &args);
    }

    // since version 3
    pub fn release(self: *Pointer) void {
        self.proxy().marshalDestructor(1, null);
    }
};

// wl_keyboard, version 11
pub const Keyboard = opaque {
    pub const generated_version: u32 = 11;

    pub const interface: *const client.Interface = &wl_keyboard_interface;

    pub fn proxy(self: *Keyboard) *client.Proxy {
        return @ptrCast(self);
    }

    pub const KeymapFormat = enum(u32) {
        no_keymap = 0,
        xkb_v1 = 1,
        _,
    };

    pub const KeyState = enum(u32) {
        released = 0,
        pressed = 1,
        repeated = 2,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 3;
    };

    pub const Event = union(enum) {
        keymap: struct {
            format: u32,
            fd: i32,
            size: u32,
        },
        enter: struct {
            serial: u32,
            surface: ?*Surface,
            keys: *const client.Array,
        },
        leave: struct {
            serial: u32,
            surface: ?*Surface,
        },
        key: struct {
            serial: u32,
            time: u32,
            key: u32,
            state: u32,
        },
        modifiers: struct {
            serial: u32,
            mods_depressed: u32,
            mods_latched: u32,
            mods_locked: u32,
            group: u32,
        },
        repeat_info: struct {
            rate: i32,
            delay: i32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .keymap = .{
                .format = args[0].u,
                .fd = args[1].h,
                .size = args[2].u,
            } },
            1 => .{ .enter = .{
                .serial = args[0].u,
                .surface = @ptrCast(args[1].o),
                .keys = args[2].a.?,
            } },
            2 => .{ .leave = .{
                .serial = args[0].u,
                .surface = @ptrCast(args[1].o),
            } },
            3 => .{ .key = .{
                .serial = args[0].u,
                .time = args[1].u,
                .key = args[2].u,
                .state = args[3].u,
            } },
            4 => .{ .modifiers = .{
                .serial = args[0].u,
                .mods_depressed = args[1].u,
                .mods_latched = args[2].u,
                .mods_locked = args[3].u,
                .group = args[4].u,
            } },
            5 => .{ .repeat_info = .{
                .rate = args[0].i,
                .delay = args[1].i,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Keyboard,
        comptime T: type,
        comptime handler: fn (*Keyboard, Event, T) void,
        data: T,
    ) void {
        client.addListener(Keyboard, Event, decodeEvent, T, handler, self, data);
    }

    // since version 3
    pub fn release(self: *Keyboard) void {
        self.proxy().marshalDestructor(0, null);
    }
};

// wl_touch, version 11
pub const Touch = opaque {
    pub const generated_version: u32 = 11;

    pub const interface: *const client.Interface = &wl_touch_interface;

    pub fn proxy(self: *Touch) *client.Proxy {
        return @ptrCast(self);
    }

    pub const since = struct {
        pub const release: u32 = 3;
    };

    pub const Event = union(enum) {
        down: struct {
            serial: u32,
            time: u32,
            surface: ?*Surface,
            id: i32,
            x: client.Fixed,
            y: client.Fixed,
        },
        up: struct {
            serial: u32,
            time: u32,
            id: i32,
        },
        motion: struct {
            time: u32,
            id: i32,
            x: client.Fixed,
            y: client.Fixed,
        },
        frame,
        cancel,
        shape: struct {
            id: i32,
            major: client.Fixed,
            minor: client.Fixed,
        },
        orientation: struct {
            id: i32,
            orientation: client.Fixed,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .down = .{
                .serial = args[0].u,
                .time = args[1].u,
                .surface = @ptrCast(args[2].o),
                .id = args[3].i,
                .x = args[4].f,
                .y = args[5].f,
            } },
            1 => .{ .up = .{
                .serial = args[0].u,
                .time = args[1].u,
                .id = args[2].i,
            } },
            2 => .{ .motion = .{
                .time = args[0].u,
                .id = args[1].i,
                .x = args[2].f,
                .y = args[3].f,
            } },
            3 => .frame,
            4 => .cancel,
            5 => .{ .shape = .{
                .id = args[0].i,
                .major = args[1].f,
                .minor = args[2].f,
            } },
            6 => .{ .orientation = .{
                .id = args[0].i,
                .orientation = args[1].f,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Touch,
        comptime T: type,
        comptime handler: fn (*Touch, Event, T) void,
        data: T,
    ) void {
        client.addListener(Touch, Event, decodeEvent, T, handler, self, data);
    }

    // since version 3
    pub fn release(self: *Touch) void {
        self.proxy().marshalDestructor(0, null);
    }
};

// wl_output, version 4
pub const Output = opaque {
    pub const generated_version: u32 = 4;

    pub const interface: *const client.Interface = &wl_output_interface;

    pub fn proxy(self: *Output) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Subpixel = enum(u32) {
        unknown = 0,
        none = 1,
        horizontal_rgb = 2,
        horizontal_bgr = 3,
        vertical_rgb = 4,
        vertical_bgr = 5,
        _,
    };

    pub const Transform = enum(u32) {
        normal = 0,
        @"90" = 1,
        @"180" = 2,
        @"270" = 3,
        flipped = 4,
        flipped_90 = 5,
        flipped_180 = 6,
        flipped_270 = 7,
        _,
    };

    pub const Mode = enum(u32) {
        current = 1,
        preferred = 2,
        _,
    };

    pub const since = struct {
        pub const release: u32 = 3;
    };

    pub const Event = union(enum) {
        geometry: struct {
            x: i32,
            y: i32,
            physical_width: i32,
            physical_height: i32,
            subpixel: i32,
            make: [*:0]const u8,
            model: [*:0]const u8,
            transform: i32,
        },
        mode: struct {
            flags: u32,
            width: i32,
            height: i32,
            refresh: i32,
        },
        done,
        scale: struct {
            factor: i32,
        },
        name: struct {
            name: [*:0]const u8,
        },
        description: struct {
            description: [*:0]const u8,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .geometry = .{
                .x = args[0].i,
                .y = args[1].i,
                .physical_width = args[2].i,
                .physical_height = args[3].i,
                .subpixel = args[4].i,
                .make = args[5].s.?,
                .model = args[6].s.?,
                .transform = args[7].i,
            } },
            1 => .{ .mode = .{
                .flags = args[0].u,
                .width = args[1].i,
                .height = args[2].i,
                .refresh = args[3].i,
            } },
            2 => .done,
            3 => .{ .scale = .{
                .factor = args[0].i,
            } },
            4 => .{ .name = .{
                .name = args[0].s.?,
            } },
            5 => .{ .description = .{
                .description = args[0].s.?,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Output,
        comptime T: type,
        comptime handler: fn (*Output, Event, T) void,
        data: T,
    ) void {
        client.addListener(Output, Event, decodeEvent, T, handler, self, data);
    }

    // since version 3
    pub fn release(self: *Output) void {
        self.proxy().marshalDestructor(0, null);
    }
};

// wl_region, version 7
pub const Region = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &wl_region_interface;

    pub fn proxy(self: *Region) *client.Proxy {
        return @ptrCast(self);
    }

    pub fn destroy(self: *Region) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn add(self: *Region, x: i32, y: i32, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn subtract(self: *Region, x: i32, y: i32, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(2, &args);
    }
};

// wl_subcompositor, version 1
pub const Subcompositor = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_subcompositor_interface;

    pub fn proxy(self: *Subcompositor) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        bad_surface = 0,
        bad_parent = 1,
        _,
    };

    pub fn destroy(self: *Subcompositor) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getSubsurface(self: *Subcompositor, surface: *Surface, parent: *Surface) client.CreateError!*Subsurface {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
            .{ .o = @ptrCast(parent) },
        };
        const created = self.proxy().marshalConstructor(1, Subsurface.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// wl_subsurface, version 1
pub const Subsurface = opaque {
    pub const generated_version: u32 = 1;

    pub const interface: *const client.Interface = &wl_subsurface_interface;

    pub fn proxy(self: *Subsurface) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        bad_surface = 0,
        _,
    };

    pub fn destroy(self: *Subsurface) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setPosition(self: *Subsurface, x: i32, y: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn placeAbove(self: *Subsurface, sibling: *Surface) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(sibling) },
        };
        self.proxy().marshal(2, &args);
    }

    pub fn placeBelow(self: *Subsurface, sibling: *Surface) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(sibling) },
        };
        self.proxy().marshal(3, &args);
    }

    pub fn setSync(self: *Subsurface) void {
        self.proxy().marshal(4, null);
    }

    pub fn setDesync(self: *Subsurface) void {
        self.proxy().marshal(5, null);
    }
};

// wl_fixes, version 2
pub const Fixes = opaque {
    pub const generated_version: u32 = 2;

    pub const interface: *const client.Interface = &wl_fixes_interface;

    pub fn proxy(self: *Fixes) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_ack_remove = 0,
        _,
    };

    pub const since = struct {
        pub const ackGlobalRemove: u32 = 2;
    };

    pub fn destroy(self: *Fixes) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn destroyRegistry(self: *Fixes, registry: *Registry) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(registry) },
        };
        self.proxy().marshal(1, &args);
    }

    // since version 2
    pub fn ackGlobalRemove(self: *Fixes, registry: *Registry, name: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(registry) },
            .{ .u = name },
        };
        self.proxy().marshal(2, &args);
    }
};
