// Generated by tools/scanner.zig from protocols/xdg-shell.xml. Do not edit.

const client = @import("../client.zig");
const wayland = @import("wayland.zig");

// xdg_wm_base, version 7
pub const WmBase = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "xdg_wm_base",
        .version = 7,
        .method_count = 4,
        .methods = &requests,
        .event_count = 1,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "create_positioner", .signature = "n", .types = &[_]?*const client.Interface{Positioner.interface} },
        .{ .name = "get_xdg_surface", .signature = "no", .types = &[_]?*const client.Interface{ Surface.interface, wayland.Surface.interface } },
        .{ .name = "pong", .signature = "u", .types = &[_]?*const client.Interface{null} },
    };

    const events = [_]client.Message{
        .{ .name = "ping", .signature = "u", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *WmBase) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        role = 0,
        defunct_surfaces = 1,
        not_the_topmost_popup = 2,
        invalid_popup_parent = 3,
        invalid_surface_state = 4,
        invalid_positioner = 5,
        unresponsive = 6,
        _,
    };

    pub const Event = union(enum) {
        ping: struct {
            serial: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .ping = .{
                .serial = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *WmBase,
        comptime T: type,
        comptime handler: fn (*WmBase, Event, T) void,
        data: T,
    ) void {
        client.addListener(WmBase, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *WmBase) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn createPositioner(self: *WmBase) client.CreateError!*Positioner {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(1, Positioner.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn getXdgSurface(self: *WmBase, surface: *wayland.Surface) client.CreateError!*Surface {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(surface) },
        };
        const created = self.proxy().marshalConstructor(2, Surface.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn pong(self: *WmBase, serial: u32) void {
        var args = [_]client.Argument{
            .{ .u = serial },
        };
        self.proxy().marshal(3, &args);
    }
};

// xdg_positioner, version 7
pub const Positioner = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "xdg_positioner",
        .version = 7,
        .method_count = 10,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_size", .signature = "ii", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "set_anchor_rect", .signature = "iiii", .types = &[_]?*const client.Interface{ null, null, null, null } },
        .{ .name = "set_anchor", .signature = "u", .types = &[_]?*const client.Interface{null} },
        .{ .name = "set_gravity", .signature = "u", .types = &[_]?*const client.Interface{null} },
        .{ .name = "set_constraint_adjustment", .signature = "u", .types = &[_]?*const client.Interface{null} },
        .{ .name = "set_offset", .signature = "ii", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "set_reactive", .signature = "3", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_parent_size", .signature = "3ii", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "set_parent_configure", .signature = "3u", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *Positioner) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_input = 0,
        _,
    };

    pub const Anchor = enum(u32) {
        none = 0,
        top = 1,
        bottom = 2,
        left = 3,
        right = 4,
        top_left = 5,
        bottom_left = 6,
        top_right = 7,
        bottom_right = 8,
        _,
    };

    pub const Gravity = enum(u32) {
        none = 0,
        top = 1,
        bottom = 2,
        left = 3,
        right = 4,
        top_left = 5,
        bottom_left = 6,
        top_right = 7,
        bottom_right = 8,
        _,
    };

    pub const ConstraintAdjustment = enum(u32) {
        none = 0,
        slide_x = 1,
        slide_y = 2,
        flip_x = 4,
        flip_y = 8,
        resize_x = 16,
        resize_y = 32,
        _,
    };

    pub const since = struct {
        pub const setReactive: u32 = 3;
        pub const setParentSize: u32 = 3;
        pub const setParentConfigure: u32 = 3;
    };

    pub fn destroy(self: *Positioner) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setSize(self: *Positioner, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn setAnchorRect(self: *Positioner, x: i32, y: i32, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(2, &args);
    }

    pub fn setAnchor(self: *Positioner, anchor: Anchor) void {
        var args = [_]client.Argument{
            .{ .u = @intFromEnum(anchor) },
        };
        self.proxy().marshal(3, &args);
    }

    pub fn setGravity(self: *Positioner, gravity: Gravity) void {
        var args = [_]client.Argument{
            .{ .u = @intFromEnum(gravity) },
        };
        self.proxy().marshal(4, &args);
    }

    pub fn setConstraintAdjustment(self: *Positioner, constraint_adjustment: ConstraintAdjustment) void {
        var args = [_]client.Argument{
            .{ .u = @intFromEnum(constraint_adjustment) },
        };
        self.proxy().marshal(5, &args);
    }

    pub fn setOffset(self: *Positioner, x: i32, y: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
        };
        self.proxy().marshal(6, &args);
    }

    // since version 3
    pub fn setReactive(self: *Positioner) void {
        self.proxy().marshal(7, null);
    }

    // since version 3
    pub fn setParentSize(self: *Positioner, parent_width: i32, parent_height: i32) void {
        var args = [_]client.Argument{
            .{ .i = parent_width },
            .{ .i = parent_height },
        };
        self.proxy().marshal(8, &args);
    }

    // since version 3
    pub fn setParentConfigure(self: *Positioner, serial: u32) void {
        var args = [_]client.Argument{
            .{ .u = serial },
        };
        self.proxy().marshal(9, &args);
    }
};

// xdg_surface, version 7
pub const Surface = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "xdg_surface",
        .version = 7,
        .method_count = 5,
        .methods = &requests,
        .event_count = 1,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "get_toplevel", .signature = "n", .types = &[_]?*const client.Interface{Toplevel.interface} },
        .{ .name = "get_popup", .signature = "n?oo", .types = &[_]?*const client.Interface{ Popup.interface, Surface.interface, Positioner.interface } },
        .{ .name = "set_window_geometry", .signature = "iiii", .types = &[_]?*const client.Interface{ null, null, null, null } },
        .{ .name = "ack_configure", .signature = "u", .types = &[_]?*const client.Interface{null} },
    };

    const events = [_]client.Message{
        .{ .name = "configure", .signature = "u", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *Surface) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        not_constructed = 1,
        already_constructed = 2,
        unconfigured_buffer = 3,
        invalid_serial = 4,
        invalid_size = 5,
        defunct_role_object = 6,
        _,
    };

    pub const Event = union(enum) {
        configure: struct {
            serial: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .configure = .{
                .serial = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Surface,
        comptime T: type,
        comptime handler: fn (*Surface, Event, T) void,
        data: T,
    ) void {
        client.addListener(Surface, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *Surface) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getToplevel(self: *Surface) client.CreateError!*Toplevel {
        var args = [_]client.Argument{
            .{ .n = 0 },
        };
        const created = self.proxy().marshalConstructor(1, Toplevel.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn getPopup(self: *Surface, parent: ?*Surface, positioner: *Positioner) client.CreateError!*Popup {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(parent) },
            .{ .o = @ptrCast(positioner) },
        };
        const created = self.proxy().marshalConstructor(2, Popup.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }

    pub fn setWindowGeometry(self: *Surface, x: i32, y: i32, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = x },
            .{ .i = y },
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(3, &args);
    }

    pub fn ackConfigure(self: *Surface, serial: u32) void {
        var args = [_]client.Argument{
            .{ .u = serial },
        };
        self.proxy().marshal(4, &args);
    }
};

// xdg_toplevel, version 7
pub const Toplevel = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "xdg_toplevel",
        .version = 7,
        .method_count = 14,
        .methods = &requests,
        .event_count = 4,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_parent", .signature = "?o", .types = &[_]?*const client.Interface{Toplevel.interface} },
        .{ .name = "set_title", .signature = "s", .types = &[_]?*const client.Interface{null} },
        .{ .name = "set_app_id", .signature = "s", .types = &[_]?*const client.Interface{null} },
        .{ .name = "show_window_menu", .signature = "ouii", .types = &[_]?*const client.Interface{ wayland.Seat.interface, null, null, null } },
        .{ .name = "move", .signature = "ou", .types = &[_]?*const client.Interface{ wayland.Seat.interface, null } },
        .{ .name = "resize", .signature = "ouu", .types = &[_]?*const client.Interface{ wayland.Seat.interface, null, null } },
        .{ .name = "set_max_size", .signature = "ii", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "set_min_size", .signature = "ii", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "set_maximized", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "unset_maximized", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_fullscreen", .signature = "?o", .types = &[_]?*const client.Interface{wayland.Output.interface} },
        .{ .name = "unset_fullscreen", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_minimized", .signature = "", .types = &[_]?*const client.Interface{} },
    };

    const events = [_]client.Message{
        .{ .name = "configure", .signature = "iia", .types = &[_]?*const client.Interface{ null, null, null } },
        .{ .name = "close", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "configure_bounds", .signature = "4ii", .types = &[_]?*const client.Interface{ null, null } },
        .{ .name = "wm_capabilities", .signature = "5a", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *Toplevel) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_resize_edge = 0,
        invalid_parent = 1,
        invalid_size = 2,
        _,
    };

    pub const ResizeEdge = enum(u32) {
        none = 0,
        top = 1,
        bottom = 2,
        left = 4,
        top_left = 5,
        bottom_left = 6,
        right = 8,
        top_right = 9,
        bottom_right = 10,
        _,
    };

    pub const State = enum(u32) {
        maximized = 1,
        fullscreen = 2,
        resizing = 3,
        activated = 4,
        tiled_left = 5,
        tiled_right = 6,
        tiled_top = 7,
        tiled_bottom = 8,
        suspended = 9,
        constrained_left = 10,
        constrained_right = 11,
        constrained_top = 12,
        constrained_bottom = 13,
        _,
    };

    pub const WmCapabilities = enum(u32) {
        window_menu = 1,
        maximize = 2,
        fullscreen = 3,
        minimize = 4,
        _,
    };

    pub const Event = union(enum) {
        configure: struct {
            width: i32,
            height: i32,
            states: *const client.Array,
        },
        close,
        configure_bounds: struct {
            width: i32,
            height: i32,
        },
        wm_capabilities: struct {
            capabilities: *const client.Array,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .configure = .{
                .width = args[0].i,
                .height = args[1].i,
                .states = args[2].a.?,
            } },
            1 => .close,
            2 => .{ .configure_bounds = .{
                .width = args[0].i,
                .height = args[1].i,
            } },
            3 => .{ .wm_capabilities = .{
                .capabilities = args[0].a.?,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Toplevel,
        comptime T: type,
        comptime handler: fn (*Toplevel, Event, T) void,
        data: T,
    ) void {
        client.addListener(Toplevel, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *Toplevel) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setParent(self: *Toplevel, parent: ?*Toplevel) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(parent) },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn setTitle(self: *Toplevel, title: [*:0]const u8) void {
        var args = [_]client.Argument{
            .{ .s = title },
        };
        self.proxy().marshal(2, &args);
    }

    pub fn setAppId(self: *Toplevel, app_id: [*:0]const u8) void {
        var args = [_]client.Argument{
            .{ .s = app_id },
        };
        self.proxy().marshal(3, &args);
    }

    pub fn showWindowMenu(self: *Toplevel, seat: *wayland.Seat, serial: u32, x: i32, y: i32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
            .{ .i = x },
            .{ .i = y },
        };
        self.proxy().marshal(4, &args);
    }

    pub fn move(self: *Toplevel, seat: *wayland.Seat, serial: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
        };
        self.proxy().marshal(5, &args);
    }

    pub fn resize(self: *Toplevel, seat: *wayland.Seat, serial: u32, edges: ResizeEdge) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
            .{ .u = @intFromEnum(edges) },
        };
        self.proxy().marshal(6, &args);
    }

    pub fn setMaxSize(self: *Toplevel, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(7, &args);
    }

    pub fn setMinSize(self: *Toplevel, width: i32, height: i32) void {
        var args = [_]client.Argument{
            .{ .i = width },
            .{ .i = height },
        };
        self.proxy().marshal(8, &args);
    }

    pub fn setMaximized(self: *Toplevel) void {
        self.proxy().marshal(9, null);
    }

    pub fn unsetMaximized(self: *Toplevel) void {
        self.proxy().marshal(10, null);
    }

    pub fn setFullscreen(self: *Toplevel, output: ?*wayland.Output) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(output) },
        };
        self.proxy().marshal(11, &args);
    }

    pub fn unsetFullscreen(self: *Toplevel) void {
        self.proxy().marshal(12, null);
    }

    pub fn setMinimized(self: *Toplevel) void {
        self.proxy().marshal(13, null);
    }
};

// xdg_popup, version 7
pub const Popup = opaque {
    pub const generated_version: u32 = 7;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "xdg_popup",
        .version = 7,
        .method_count = 3,
        .methods = &requests,
        .event_count = 3,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "grab", .signature = "ou", .types = &[_]?*const client.Interface{ wayland.Seat.interface, null } },
        .{ .name = "reposition", .signature = "3ou", .types = &[_]?*const client.Interface{ Positioner.interface, null } },
    };

    const events = [_]client.Message{
        .{ .name = "configure", .signature = "iiii", .types = &[_]?*const client.Interface{ null, null, null, null } },
        .{ .name = "popup_done", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "repositioned", .signature = "3u", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *Popup) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        invalid_grab = 0,
        _,
    };

    pub const since = struct {
        pub const reposition: u32 = 3;
    };

    pub const Event = union(enum) {
        configure: struct {
            x: i32,
            y: i32,
            width: i32,
            height: i32,
        },
        popup_done,
        repositioned: struct {
            token: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .configure = .{
                .x = args[0].i,
                .y = args[1].i,
                .width = args[2].i,
                .height = args[3].i,
            } },
            1 => .popup_done,
            2 => .{ .repositioned = .{
                .token = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *Popup,
        comptime T: type,
        comptime handler: fn (*Popup, Event, T) void,
        data: T,
    ) void {
        client.addListener(Popup, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *Popup) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn grab(self: *Popup, seat: *wayland.Seat, serial: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(seat) },
            .{ .u = serial },
        };
        self.proxy().marshal(1, &args);
    }

    // since version 3
    pub fn reposition(self: *Popup, positioner: *Positioner, token: u32) void {
        var args = [_]client.Argument{
            .{ .o = @ptrCast(positioner) },
            .{ .u = token },
        };
        self.proxy().marshal(2, &args);
    }
};
