// Generated by tools/scanner.zig from protocols/xdg-decoration-unstable-v1.xml. Do not edit.

const client = @import("../client.zig");
const xdg_shell = @import("xdg_shell.zig");

// zxdg_decoration_manager_v1, version 2
pub const DecorationManagerV1 = opaque {
    pub const generated_version: u32 = 2;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zxdg_decoration_manager_v1",
        .version = 2,
        .method_count = 2,
        .methods = &requests,
        .event_count = 0,
        .events = null,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "get_toplevel_decoration", .signature = "no", .types = &[_]?*const client.Interface{ ToplevelDecorationV1.interface, xdg_shell.Toplevel.interface } },
    };

    pub fn proxy(self: *DecorationManagerV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub fn destroy(self: *DecorationManagerV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn getToplevelDecoration(self: *DecorationManagerV1, toplevel: *xdg_shell.Toplevel) client.CreateError!*ToplevelDecorationV1 {
        var args = [_]client.Argument{
            .{ .n = 0 },
            .{ .o = @ptrCast(toplevel) },
        };
        const created = self.proxy().marshalConstructor(1, ToplevelDecorationV1.interface, &args) orelse
            return error.ProxyCreationFailed;
        return @ptrCast(created);
    }
};

// zxdg_toplevel_decoration_v1, version 2
pub const ToplevelDecorationV1 = opaque {
    pub const generated_version: u32 = 2;

    pub const interface: *const client.Interface = &table;

    const table: client.Interface = .{
        .name = "zxdg_toplevel_decoration_v1",
        .version = 2,
        .method_count = 3,
        .methods = &requests,
        .event_count = 1,
        .events = &events,
    };

    const requests = [_]client.Message{
        .{ .name = "destroy", .signature = "", .types = &[_]?*const client.Interface{} },
        .{ .name = "set_mode", .signature = "u", .types = &[_]?*const client.Interface{null} },
        .{ .name = "unset_mode", .signature = "", .types = &[_]?*const client.Interface{} },
    };

    const events = [_]client.Message{
        .{ .name = "configure", .signature = "u", .types = &[_]?*const client.Interface{null} },
    };

    pub fn proxy(self: *ToplevelDecorationV1) *client.Proxy {
        return @ptrCast(self);
    }

    pub const Error = enum(u32) {
        unconfigured_buffer = 0,
        already_constructed = 1,
        orphaned = 2,
        invalid_mode = 3,
        _,
    };

    pub const Mode = enum(u32) {
        client_side = 1,
        server_side = 2,
        _,
    };

    pub const Event = union(enum) {
        configure: struct {
            mode: u32,
        },
    };

    // libwayland rejects an opcode outside this interface's own event
    // table before an event is queued, so the switch is total over what
    // can arrive.
    fn decodeEvent(opcode: u32, args: [*]client.Argument) Event {
        return switch (opcode) {
            0 => .{ .configure = .{
                .mode = args[0].u,
            } },
            else => unreachable,
        };
    }

    pub fn setListener(
        self: *ToplevelDecorationV1,
        comptime T: type,
        comptime handler: fn (*ToplevelDecorationV1, Event, T) void,
        data: T,
    ) void {
        client.addListener(ToplevelDecorationV1, Event, decodeEvent, T, handler, self, data);
    }

    pub fn destroy(self: *ToplevelDecorationV1) void {
        self.proxy().marshalDestructor(0, null);
    }

    pub fn setMode(self: *ToplevelDecorationV1, mode: Mode) void {
        var args = [_]client.Argument{
            .{ .u = @backingInt(mode) },
        };
        self.proxy().marshal(1, &args);
    }

    pub fn unsetMode(self: *ToplevelDecorationV1) void {
        self.proxy().marshal(2, null);
    }
};
