const std = @import("std");

// Generates Zig bindings from Wayland protocol XML.
//
// Tooling. The output is committed under src/backend/linux/wl/protocol/ and is
// regenerated by `zig build protocols`, so an ordinary build runs no code
// generation and an editor sees ordinary files.
//
// Every input is parsed before anything is emitted, because an interface may be
// referenced from a protocol that does not define it: xdg-shell names
// wl_surface, xdg-decoration names xdg_toplevel. The index built in the first
// pass is what turns such a reference into an import.
//
// Usage: scanner <out-dir> <protocol.xml>...

const usage = "usage: scanner <out-dir> <protocol.xml>...\n";

// Namespace prefixes used by wayland-protocols. Stripping them is what turns
// `xdg_wm_base` into `xdg_shell.WmBase` instead of `xdg_shell.XdgWmBase`. The
// longer spellings come first so that `zwp_` is not read as `wp_` with a stray z.
const namespace_prefixes = [_][]const u8{ "zwp_", "zxdg_", "wl_", "wp_", "xdg_" };

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;

    var argv = try std.process.Args.Iterator.initAllocator(init.minimal.args, arena);
    defer argv.deinit();
    _ = argv.skip();

    var paths: std.ArrayList([]const u8) = .empty;
    while (argv.next()) |arg| try paths.append(arena, arg);
    if (paths.items.len < 2) {
        std.debug.print(usage, .{});
        return error.InvalidUsage;
    }

    const out_dir_path = paths.items[0];
    const inputs = paths.items[1..];

    const cwd: std.Io.Dir = .cwd();

    var protocols: std.ArrayList(Protocol) = .empty;
    for (inputs) |path| {
        const source = cwd.readFileAlloc(io, path, arena, .limited(8 << 20)) catch |err| {
            std.debug.print("cannot read {s}: {t}\n", .{ path, err });
            return err;
        };
        var protocol = try parse(arena, source);
        protocol.file_stem = try fileStem(arena, path);
        protocol.source_name = std.fs.path.basename(path);
        try protocols.append(arena, protocol);
    }

    // Interface name to the protocol that defines it. A reference that misses
    // here is generated as neither a type nor a table entry; see emitRequest.
    var index: std.StringHashMapUnmanaged(usize) = .empty;
    for (protocols.items, 0..) |protocol, i| {
        for (protocol.interfaces.items) |interface| {
            try index.put(arena, interface.name, i);
        }
    }

    try cwd.createDirPath(io, out_dir_path);
    var out_dir = try cwd.openDir(io, out_dir_path, .{});
    defer out_dir.close(io);

    for (protocols.items, 0..) |protocol, i| {
        var text: std.ArrayList(u8) = .empty;
        try emitProtocol(arena, &text, protocols.items, index, i);

        const name = try std.fmt.allocPrint(arena, "{s}.zig", .{protocol.file_stem});
        try out_dir.writeFile(io, .{ .sub_path = name, .data = text.items });
        std.debug.print("{s}: {d} interfaces\n", .{ name, protocol.interfaces.items.len });
    }
}

// The model
// =========

const ArgType = enum {
    int,
    uint,
    fixed,
    string,
    object,
    new_id,
    array,
    fd,

    fn parse(text: []const u8) !ArgType {
        const map = .{
            .{ "int", ArgType.int },
            .{ "uint", ArgType.uint },
            .{ "fixed", ArgType.fixed },
            .{ "string", ArgType.string },
            .{ "object", ArgType.object },
            .{ "new_id", ArgType.new_id },
            .{ "array", ArgType.array },
            .{ "fd", ArgType.fd },
        };
        inline for (map) |entry| {
            if (std.mem.eql(u8, text, entry[0])) return entry[1];
        }
        return error.UnknownArgType;
    }

    // The character this type contributes to a wl_message signature
    // (wayland-util.h, wl_message.signature).
    fn signatureChar(self: ArgType) u8 {
        return switch (self) {
            .int => 'i',
            .uint => 'u',
            .fixed => 'f',
            .string => 's',
            .object => 'o',
            .new_id => 'n',
            .array => 'a',
            .fd => 'h',
        };
    }
};

const Arg = struct {
    name: []const u8,
    type: ArgType,
    interface: ?[]const u8 = null,
    allow_null: bool = false,
    enum_ref: ?[]const u8 = null,
};

const Message = struct {
    name: []const u8,
    since: u32 = 1,
    destructor: bool = false,
    args: std.ArrayList(Arg) = .empty,
};

const EnumEntry = struct {
    name: []const u8,
    value: u32,
};

const Enum = struct {
    name: []const u8,
    entries: std.ArrayList(EnumEntry) = .empty,
};

const Interface = struct {
    name: []const u8,
    version: u32,
    requests: std.ArrayList(Message) = .empty,
    events: std.ArrayList(Message) = .empty,
    enums: std.ArrayList(Enum) = .empty,
};

const Protocol = struct {
    name: []const u8,
    file_stem: []const u8 = "",
    source_name: []const u8 = "",
    interfaces: std.ArrayList(Interface) = .empty,
};

// XML
// ===

// A pull parser over the subset wayland.dtd describes: elements, attributes,
// and character data that this generator never reads. Comments, the XML
// declaration and a doctype are skipped. Entity references appear only inside
// `summary` and `description`, neither of which is emitted, so none are decoded.
const Reader = struct {
    source: []const u8,
    pos: usize = 0,

    const Attr = struct { name: []const u8, value: []const u8 };

    const Token = union(enum) {
        open: struct { name: []const u8, attrs: []const Attr, empty: bool },
        close: []const u8,
        eof,
    };

    fn next(self: *Reader, arena: std.mem.Allocator) !Token {
        while (true) {
            const lt = std.mem.indexOfScalarPos(u8, self.source, self.pos, '<') orelse {
                self.pos = self.source.len;
                return .eof;
            };
            self.pos = lt + 1;
            const rest = self.source[self.pos..];

            if (std.mem.startsWith(u8, rest, "!--")) {
                const end = std.mem.indexOfPos(u8, self.source, self.pos, "-->") orelse
                    return error.UnterminatedComment;
                self.pos = end + 3;
                continue;
            }
            if (rest.len != 0 and (rest[0] == '?' or rest[0] == '!')) {
                const end = std.mem.indexOfScalarPos(u8, self.source, self.pos, '>') orelse
                    return error.UnterminatedDeclaration;
                self.pos = end + 1;
                continue;
            }
            if (rest.len != 0 and rest[0] == '/') {
                self.pos += 1;
                const name = self.readName();
                const end = std.mem.indexOfScalarPos(u8, self.source, self.pos, '>') orelse
                    return error.UnterminatedTag;
                self.pos = end + 1;
                return .{ .close = name };
            }

            const name = self.readName();
            var attrs: std.ArrayList(Attr) = .empty;
            while (true) {
                self.skipSpace();
                if (self.pos >= self.source.len) return error.UnterminatedTag;
                if (self.source[self.pos] == '>') {
                    self.pos += 1;
                    return .{ .open = .{ .name = name, .attrs = attrs.items, .empty = false } };
                }
                if (self.source[self.pos] == '/') {
                    self.pos += 1;
                    if (self.pos >= self.source.len or self.source[self.pos] != '>')
                        return error.UnterminatedTag;
                    self.pos += 1;
                    return .{ .open = .{ .name = name, .attrs = attrs.items, .empty = true } };
                }
                const attr_name = self.readName();
                if (attr_name.len == 0) return error.MalformedAttribute;
                self.skipSpace();
                if (self.pos >= self.source.len or self.source[self.pos] != '=')
                    return error.MalformedAttribute;
                self.pos += 1;
                self.skipSpace();
                if (self.pos >= self.source.len) return error.MalformedAttribute;
                const quote = self.source[self.pos];
                if (quote != '"' and quote != '\'') return error.MalformedAttribute;
                self.pos += 1;
                const value_start = self.pos;
                const value_end = std.mem.indexOfScalarPos(u8, self.source, self.pos, quote) orelse
                    return error.MalformedAttribute;
                self.pos = value_end + 1;
                try attrs.append(arena, .{
                    .name = attr_name,
                    .value = self.source[value_start..value_end],
                });
            }
        }
    }

    fn readName(self: *Reader) []const u8 {
        const start = self.pos;
        while (self.pos < self.source.len) : (self.pos += 1) {
            switch (self.source[self.pos]) {
                'a'...'z', 'A'...'Z', '0'...'9', '_', '-', ':', '.' => {},
                else => break,
            }
        }
        return self.source[start..self.pos];
    }

    fn skipSpace(self: *Reader) void {
        while (self.pos < self.source.len) : (self.pos += 1) {
            switch (self.source[self.pos]) {
                ' ', '\t', '\r', '\n' => {},
                else => break,
            }
        }
    }
};

fn attr(attrs: []const Reader.Attr, name: []const u8) ?[]const u8 {
    for (attrs) |a| {
        if (std.mem.eql(u8, a.name, name)) return a.value;
    }
    return null;
}

fn parse(arena: std.mem.Allocator, source: []const u8) !Protocol {
    var reader: Reader = .{ .source = source };
    var protocol: Protocol = .{ .name = "" };

    // Where the parser currently is. Indices rather than pointers: the lists
    // below are appended to while these are live, and an append that grows one
    // moves its items.
    var interface: ?usize = null;
    var message: ?struct { event: bool, index: usize } = null;
    var enumeration: ?usize = null;

    while (true) {
        const token = try reader.next(arena);
        switch (token) {
            .eof => break,
            .close => |name| {
                if (std.mem.eql(u8, name, "interface")) interface = null;
                if (std.mem.eql(u8, name, "request") or std.mem.eql(u8, name, "event")) message = null;
                if (std.mem.eql(u8, name, "enum")) enumeration = null;
            },
            .open => |element| {
                if (std.mem.eql(u8, element.name, "protocol")) {
                    protocol.name = attr(element.attrs, "name") orelse return error.MissingName;
                } else if (std.mem.eql(u8, element.name, "interface")) {
                    try protocol.interfaces.append(arena, .{
                        .name = attr(element.attrs, "name") orelse return error.MissingName,
                        .version = try std.fmt.parseInt(
                            u32,
                            attr(element.attrs, "version") orelse return error.MissingVersion,
                            10,
                        ),
                    });
                    interface = protocol.interfaces.items.len - 1;
                } else if (std.mem.eql(u8, element.name, "request") or
                    std.mem.eql(u8, element.name, "event"))
                {
                    const owner = &protocol.interfaces.items[interface orelse return error.StrayMessage];
                    const event = std.mem.eql(u8, element.name, "event");
                    const list = if (event) &owner.events else &owner.requests;
                    try list.append(arena, .{
                        .name = attr(element.attrs, "name") orelse return error.MissingName,
                        .since = if (attr(element.attrs, "since")) |s|
                            try std.fmt.parseInt(u32, s, 10)
                        else
                            1,
                        .destructor = if (attr(element.attrs, "type")) |t|
                            std.mem.eql(u8, t, "destructor")
                        else
                            false,
                    });
                    message = if (element.empty) null else .{ .event = event, .index = list.items.len - 1 };
                } else if (std.mem.eql(u8, element.name, "arg")) {
                    const at = message orelse return error.StrayArg;
                    const owner = &protocol.interfaces.items[interface.?];
                    const list = if (at.event) &owner.events else &owner.requests;
                    try list.items[at.index].args.append(arena, .{
                        .name = attr(element.attrs, "name") orelse return error.MissingName,
                        .type = try ArgType.parse(attr(element.attrs, "type") orelse
                            return error.MissingType),
                        .interface = attr(element.attrs, "interface"),
                        .allow_null = if (attr(element.attrs, "allow-null")) |v|
                            std.mem.eql(u8, v, "true")
                        else
                            false,
                        .enum_ref = attr(element.attrs, "enum"),
                    });
                } else if (std.mem.eql(u8, element.name, "enum")) {
                    const owner = &protocol.interfaces.items[interface orelse return error.StrayEnum];
                    try owner.enums.append(arena, .{
                        .name = attr(element.attrs, "name") orelse return error.MissingName,
                    });
                    enumeration = if (element.empty) null else owner.enums.items.len - 1;
                } else if (std.mem.eql(u8, element.name, "entry")) {
                    const at = enumeration orelse return error.StrayEntry;
                    const owner = &protocol.interfaces.items[interface.?];
                    const raw = attr(element.attrs, "value") orelse return error.MissingValue;
                    try owner.enums.items[at].entries.append(arena, .{
                        .name = attr(element.attrs, "name") orelse return error.MissingName,
                        // Base 0 so that the hexadecimal spellings the protocols
                        // use for bitfields parse as written.
                        .value = try std.fmt.parseInt(u32, raw, 0),
                    });
                }
            },
        }
    }
    return protocol;
}

// Naming
// ======

fn fileStem(arena: std.mem.Allocator, path: []const u8) ![]const u8 {
    const base = std.fs.path.basename(path);
    const without_ext = if (std.mem.lastIndexOfScalar(u8, base, '.')) |dot| base[0..dot] else base;
    const stem = try arena.dupe(u8, without_ext);
    for (stem) |*c| {
        if (c.* == '-') c.* = '_';
    }
    return stem;
}

fn stripNamespace(name: []const u8) []const u8 {
    for (namespace_prefixes) |prefix| {
        if (std.mem.startsWith(u8, name, prefix)) return name[prefix.len..];
    }
    return name;
}

fn pascalCase(arena: std.mem.Allocator, name: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    var upper = true;
    for (name) |c| {
        if (c == '_') {
            upper = true;
            continue;
        }
        try out.append(arena, if (upper) std.ascii.toUpper(c) else c);
        upper = false;
    }
    return out.items;
}

fn camelCase(arena: std.mem.Allocator, name: []const u8) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    var upper = false;
    for (name, 0..) |c, i| {
        if (c == '_') {
            upper = true;
            continue;
        }
        try out.append(arena, if (upper and i != 0) std.ascii.toUpper(c) else c);
        upper = false;
    }
    return out.items;
}

fn typeName(arena: std.mem.Allocator, interface_name: []const u8) ![]const u8 {
    return pascalCase(arena, stripNamespace(interface_name));
}

// Emission
// ========

const Context = struct {
    arena: std.mem.Allocator,
    protocols: []const Protocol,
    index: std.StringHashMapUnmanaged(usize),
    self: usize,

    // How the generated file names `interface_name`'s interface pointer, or
    // null when nothing in the inputs defines it.
    fn interfaceRef(self: Context, interface_name: []const u8) !?[]const u8 {
        const owner = self.index.get(interface_name) orelse return null;
        const local = try typeName(self.arena, interface_name);
        if (owner == self.self) return try std.fmt.allocPrint(self.arena, "{s}.interface", .{local});
        return try std.fmt.allocPrint(
            self.arena,
            "{s}.{s}.interface",
            .{ self.protocols[owner].file_stem, local },
        );
    }

    fn typeRef(self: Context, interface_name: []const u8) !?[]const u8 {
        const owner = self.index.get(interface_name) orelse return null;
        const local = try typeName(self.arena, interface_name);
        if (owner == self.self) return local;
        return try std.fmt.allocPrint(
            self.arena,
            "{s}.{s}",
            .{ self.protocols[owner].file_stem, local },
        );
    }
};

// wayland.xml's interfaces are compiled into libwayland-client, so a table
// generated for them here would be a second wl_interface with the same name and
// libwayland would compare the two by pointer. Those are declared extern.
fn isCore(protocol: *const Protocol) bool {
    return std.mem.eql(u8, protocol.name, "wayland");
}

fn emitProtocol(
    arena: std.mem.Allocator,
    out: *std.ArrayList(u8),
    protocols: []const Protocol,
    index: std.StringHashMapUnmanaged(usize),
    self_index: usize,
) !void {
    const protocol = &protocols[self_index];
    const context: Context = .{
        .arena = arena,
        .protocols = protocols,
        .index = index,
        .self = self_index,
    };

    try out.print(arena,
        \\// Generated by tools/scanner.zig from protocols/{s}. Do not edit.
        \\
        \\const client = @import("../client.zig");
        \\
    , .{protocol.source_name});

    // Imports, in a fixed order so that regenerating produces no diff.
    var needed: std.AutoArrayHashMapUnmanaged(usize, void) = .empty;
    for (protocol.interfaces.items) |interface| {
        for ([_][]const Message{ interface.requests.items, interface.events.items }) |list| {
            for (list) |message| {
                for (message.args.items) |arg| {
                    const name = arg.interface orelse continue;
                    const owner = index.get(name) orelse continue;
                    if (owner != self_index) try needed.put(arena, owner, {});
                }
            }
        }
    }
    const owners = needed.keys();
    std.mem.sort(usize, owners, {}, std.sort.asc(usize));
    for (owners) |owner| {
        try out.print(arena, "const {s} = @import(\"{s}.zig\");\n", .{
            protocols[owner].file_stem,
            protocols[owner].file_stem,
        });
    }

    if (isCore(protocol)) {
        try out.appendSlice(arena,
            \\
            \\// Defined by libwayland-client rather than here: the core protocol's
            \\// tables ship inside the library, and a second copy would not compare
            \\// equal to the one Vulkan's WSI and libwayland itself already use.
            \\
        );
        for (protocol.interfaces.items) |interface| {
            try out.print(arena, "extern const {s}_interface: client.Interface;\n", .{interface.name});
        }
    }

    for (protocol.interfaces.items) |*interface| {
        try emitInterface(arena, out, context, protocol, interface);
    }
}

fn emitInterface(
    arena: std.mem.Allocator,
    out: *std.ArrayList(u8),
    context: Context,
    protocol: *const Protocol,
    interface: *const Interface,
) !void {
    const name = try typeName(arena, interface.name);

    try out.print(arena, "\n// {s}, version {d}\npub const {s} = opaque {{\n", .{
        interface.name,
        interface.version,
        name,
    });

    // The version this file was generated from, which is the ceiling a bind may
    // ask for: a request newer than the bound version is a protocol error, and
    // the compositor's own ceiling is the other half of the minimum.
    try out.print(arena, "    pub const generated_version: u32 = {d};\n\n", .{interface.version});

    if (isCore(protocol)) {
        try out.print(
            arena,
            "    pub const interface: *const client.Interface = &{s}_interface;\n",
            .{interface.name},
        );
    } else {
        try out.print(arena,
            \\    pub const interface: *const client.Interface = &table;
            \\
            \\    const table: client.Interface = .{{
            \\        .name = "{s}",
            \\        .version = {d},
            \\        .method_count = {d},
            \\        .methods = {s},
            \\        .event_count = {d},
            \\        .events = {s},
            \\    }};
            \\
        , .{
            interface.name,
            interface.version,
            interface.requests.items.len,
            if (interface.requests.items.len == 0) "null" else "&requests",
            interface.events.items.len,
            if (interface.events.items.len == 0) "null" else "&events",
        });

        if (interface.requests.items.len != 0)
            try emitMessageTable(arena, out, context, "requests", interface.requests.items);
        if (interface.events.items.len != 0)
            try emitMessageTable(arena, out, context, "events", interface.events.items);
    }

    try out.print(arena,
        \\
        \\    pub fn proxy(self: *{s}) *client.Proxy {{
        \\        return @ptrCast(self);
        \\    }}
        \\
    , .{name});

    for (interface.enums.items) |enumeration| try emitEnum(arena, out, enumeration);

    try emitSince(arena, out, interface.requests.items);

    if (interface.events.items.len != 0)
        try emitEvents(arena, out, context, name, interface.events.items);

    for (interface.requests.items, 0..) |request, opcode|
        try emitRequest(arena, out, context, name, request, @intCast(opcode));

    try out.appendSlice(arena, "};\n");
}

// The interface version each request was introduced in, for callers that hold a
// proxy bound to whatever the compositor offered. Sending a request the bound
// version does not have is a protocol error and kills the connection, and the
// version is the only thing that says so.
fn emitSince(arena: std.mem.Allocator, out: *std.ArrayList(u8), requests: []const Message) !void {
    var any = false;
    for (requests) |request| {
        if (request.since > 1) any = true;
    }
    if (!any) return;

    try out.appendSlice(arena, "\n    pub const since = struct {\n");
    for (requests) |request| {
        if (request.since == 1) continue;
        try out.print(arena, "        pub const {f}: u32 = {d};\n", .{
            std.zig.fmtId(try camelCase(arena, request.name)),
            request.since,
        });
    }
    try out.appendSlice(arena, "    };\n");
}

fn signature(arena: std.mem.Allocator, message: Message) ![]const u8 {
    var out: std.ArrayList(u8) = .empty;
    // The version a message was introduced in leads the signature, once, and
    // only when it is not the interface's first version (wayland-util.h,
    // wl_message.signature).
    if (message.since > 1) try out.print(arena, "{d}", .{message.since});
    for (message.args.items) |arg| {
        if (arg.allow_null) try out.append(arena, '?');
        if (arg.type == .new_id and arg.interface == null) {
            // An untyped new_id travels as the interface name and version
            // ahead of the id, which is how wl_registry.bind names what it is
            // creating.
            try out.appendSlice(arena, "sun");
            continue;
        }
        try out.append(arena, arg.type.signatureChar());
    }
    return out.items;
}

fn emitMessageTable(
    arena: std.mem.Allocator,
    out: *std.ArrayList(u8),
    context: Context,
    table_name: []const u8,
    messages: []const Message,
) !void {
    try out.print(arena, "\n    const {s} = [_]client.Message{{\n", .{table_name});
    for (messages) |message| {
        try out.print(arena, "        .{{ .name = \"{s}\", .signature = \"{s}\", .types = &[_]?*const client.Interface{{", .{
            message.name,
            try signature(arena, message),
        });
        var first = true;
        for (message.args.items) |arg| {
            const slots: usize = if (arg.type == .new_id and arg.interface == null) 3 else 1;
            for (0..slots) |slot| {
                if (!first) try out.appendSlice(arena, ",");
                first = false;
                const named = arg.interface != null and slot == slots - 1;
                const reference = if (named) try context.interfaceRef(arg.interface.?) else null;
                if (reference) |r| {
                    try out.print(arena, " {s}", .{r});
                } else {
                    try out.appendSlice(arena, " null");
                }
            }
        }
        try out.appendSlice(arena, if (first) "} },\n" else " } },\n");
    }
    try out.appendSlice(arena, "    };\n");
}

fn emitEnum(arena: std.mem.Allocator, out: *std.ArrayList(u8), enumeration: Enum) !void {
    // Non-exhaustive throughout. The protocol's own enums grow with the
    // interface version, so a compositor may legitimately send a value this file
    // does not list, and @enumFromInt onto an exhaustive enum would be undefined
    // for it.
    try out.print(arena, "\n    pub const {f} = enum(u32) {{\n", .{
        std.zig.fmtId(try pascalCase(arena, enumeration.name)),
    });
    for (enumeration.entries.items) |entry| {
        try out.print(arena, "        {f} = {d},\n", .{ std.zig.fmtId(entry.name), entry.value });
    }
    try out.appendSlice(arena, "        _,\n    };\n");
}

// The Zig type an event delivers an argument as, and the expression that reads
// it out of the argument array.
fn eventArg(arena: std.mem.Allocator, context: Context, arg: Arg, slot: usize) !struct {
    type: []const u8,
    read: []const u8,
} {
    const read = try std.fmt.allocPrint(arena, "args[{d}]", .{slot});
    return switch (arg.type) {
        .int => .{ .type = "i32", .read = try std.fmt.allocPrint(arena, "{s}.i", .{read}) },
        .uint => .{ .type = "u32", .read = try std.fmt.allocPrint(arena, "{s}.u", .{read}) },
        .fixed => .{ .type = "client.Fixed", .read = try std.fmt.allocPrint(arena, "{s}.f", .{read}) },
        .fd => .{ .type = "i32", .read = try std.fmt.allocPrint(arena, "{s}.h", .{read}) },
        .string => .{
            .type = if (arg.allow_null) "?[*:0]const u8" else "[*:0]const u8",
            .read = if (arg.allow_null)
                try std.fmt.allocPrint(arena, "{s}.s", .{read})
            else
                try std.fmt.allocPrint(arena, "{s}.s.?", .{read}),
        },
        .array => .{
            .type = "*const client.Array",
            .read = try std.fmt.allocPrint(arena, "{s}.a.?", .{read}),
        },
        .object, .new_id => blk: {
            const target = if (arg.interface) |i| try context.typeRef(i) else null;
            const pointee = target orelse "client.Proxy";
            const nullable = arg.allow_null or arg.type == .object;
            break :blk .{
                .type = try std.fmt.allocPrint(
                    arena,
                    "{s}*{s}",
                    .{ if (nullable) "?" else "", pointee },
                ),
                .read = if (nullable)
                    try std.fmt.allocPrint(arena, "@ptrCast({s}.o)", .{read})
                else
                    try std.fmt.allocPrint(arena, "@ptrCast({s}.o.?)", .{read}),
            };
        },
    };
}

fn emitEvents(
    arena: std.mem.Allocator,
    out: *std.ArrayList(u8),
    context: Context,
    owner: []const u8,
    events: []const Message,
) !void {
    try out.appendSlice(arena, "\n    pub const Event = union(enum) {\n");
    for (events) |event| {
        if (event.args.items.len == 0) {
            try out.print(arena, "        {f},\n", .{std.zig.fmtId(event.name)});
            continue;
        }
        try out.print(arena, "        {f}: struct {{\n", .{std.zig.fmtId(event.name)});
        for (event.args.items, 0..) |arg, slot| {
            const decoded = try eventArg(arena, context, arg, slot);
            try out.print(arena, "            {f}: {s},\n", .{
                std.zig.fmtId(arg.name),
                decoded.type,
            });
        }
        try out.appendSlice(arena, "        },\n");
    }
    try out.appendSlice(arena, "    };\n");

    // Every event of some interfaces carries nothing, and Zig rejects the
    // unused parameter rather than the unread argument array.
    var any_args = false;
    for (events) |event| {
        if (event.args.items.len != 0) any_args = true;
    }
    try out.print(arena,
        \\
        \\    // libwayland rejects an opcode outside this interface's own event
        \\    // table before an event is queued, so the switch is total over what
        \\    // can arrive.
        \\    fn decodeEvent(opcode: u32, {s}: [*]client.Argument) Event {{
        \\        return switch (opcode) {{
        \\
    , .{if (any_args) "args" else "_"});
    for (events, 0..) |event, opcode| {
        if (event.args.items.len == 0) {
            try out.print(arena, "            {d} => .{f},\n", .{ opcode, std.zig.fmtId(event.name) });
            continue;
        }
        try out.print(arena, "            {d} => .{{ .{f} = .{{\n", .{ opcode, std.zig.fmtId(event.name) });
        for (event.args.items, 0..) |arg, slot| {
            const decoded = try eventArg(arena, context, arg, slot);
            try out.print(arena, "                .{f} = {s},\n", .{
                std.zig.fmtId(arg.name),
                decoded.read,
            });
        }
        try out.appendSlice(arena, "            } },\n");
    }
    try out.appendSlice(arena, "            else => unreachable,\n        };\n    }\n");

    try out.print(arena,
        \\
        \\    pub fn setListener(
        \\        self: *{0s},
        \\        comptime T: type,
        \\        comptime handler: fn (*{0s}, Event, T) void,
        \\        data: T,
        \\    ) void {{
        \\        client.addListener({0s}, Event, decodeEvent, T, handler, self, data);
        \\    }}
        \\
    , .{owner});
}

fn emitRequest(
    arena: std.mem.Allocator,
    out: *std.ArrayList(u8),
    context: Context,
    owner: []const u8,
    request: Message,
    opcode: u32,
) !void {
    // An argument naming an interface no input defines cannot be given a type
    // here, and a null in its place in the table would be a claim about the
    // protocol. The message keeps its slot so that the opcodes after it stay
    // where they are, and no way to send it is generated.
    for (request.args.items) |arg| {
        const named = arg.interface orelse continue;
        if (context.index.get(named) == null) {
            try out.print(arena,
                \\
                \\    // {s} is not generated: its `{s}` argument names {s}, which is
                \\    // not among the vendored protocols.
                \\
            , .{ request.name, arg.name, named });
            return;
        }
    }

    var returns: ?Arg = null;
    for (request.args.items) |arg| {
        if (arg.type == .new_id) returns = arg;
    }

    var params: std.ArrayList(u8) = .empty;
    for (request.args.items) |arg| {
        if (arg.type == .new_id) {
            // wl_registry.bind names neither interface nor version in the
            // protocol, so the caller supplies both and the type it wants back.
            if (arg.interface == null)
                try params.appendSlice(arena, ", comptime T: type, version: u32");
            continue;
        }
        const zig_type: []const u8 = switch (arg.type) {
            .int => if (arg.enum_ref) |e| try enumRef(arena, context, e) else "i32",
            .uint => if (arg.enum_ref) |e| try enumRef(arena, context, e) else "u32",
            .fixed => "client.Fixed",
            .fd => "i32",
            .string => if (arg.allow_null) "?[*:0]const u8" else "[*:0]const u8",
            .array => "*const client.Array",
            .object => blk: {
                const target = (try context.typeRef(arg.interface.?));
                break :blk try std.fmt.allocPrint(
                    arena,
                    "{s}*{s}",
                    .{ if (arg.allow_null) "?" else "", target.? },
                );
            },
            .new_id => unreachable,
        };
        try params.print(arena, ", {f}: {s}", .{ std.zig.fmtId(arg.name), zig_type });
    }

    const return_type: []const u8 = if (returns) |arg|
        if (arg.interface) |named|
            try std.fmt.allocPrint(arena, "client.CreateError!*{s}", .{(try context.typeRef(named)).?})
        else
            "client.CreateError!*T"
    else
        "void";

    if (request.since > 1)
        try out.print(arena, "\n    // since version {d}\n", .{request.since})
    else
        try out.appendSlice(arena, "\n");

    try out.print(arena, "    pub fn {f}(self: *{s}{s}) {s} {{\n", .{
        std.zig.fmtId(try camelCase(arena, request.name)),
        owner,
        params.items,
        return_type,
    });

    // The argument array. Its slots are positional and libwayland fills the
    // new_id one in, so it is built even when every value in it is a constant.
    if (request.args.items.len != 0) {
        try out.appendSlice(arena, "        var args = [_]client.Argument{\n");
        for (request.args.items) |arg| {
            if (arg.type == .new_id) {
                if (arg.interface == null) {
                    try out.appendSlice(arena,
                        \\            .{ .s = T.interface.name },
                        \\            .{ .u = version },
                        \\
                    );
                }
                try out.appendSlice(arena, "            .{ .n = 0 },\n");
                continue;
            }
            const id = try std.fmt.allocPrint(arena, "{f}", .{std.zig.fmtId(arg.name)});
            const value: []const u8 = switch (arg.type) {
                .int => if (arg.enum_ref != null)
                    try std.fmt.allocPrint(arena, ".{{ .i = @intCast(@intFromEnum({s})) }}", .{id})
                else
                    try std.fmt.allocPrint(arena, ".{{ .i = {s} }}", .{id}),
                .uint => if (arg.enum_ref != null)
                    try std.fmt.allocPrint(arena, ".{{ .u = @intFromEnum({s}) }}", .{id})
                else
                    try std.fmt.allocPrint(arena, ".{{ .u = {s} }}", .{id}),
                .fixed => try std.fmt.allocPrint(arena, ".{{ .f = {s} }}", .{id}),
                .fd => try std.fmt.allocPrint(arena, ".{{ .h = {s} }}", .{id}),
                .string => try std.fmt.allocPrint(arena, ".{{ .s = {s} }}", .{id}),
                .array => try std.fmt.allocPrint(arena, ".{{ .a = @constCast({s}) }}", .{id}),
                .object => try std.fmt.allocPrint(arena, ".{{ .o = @ptrCast({s}) }}", .{id}),
                .new_id => unreachable,
            };
            try out.print(arena, "            {s},\n", .{value});
        }
        try out.appendSlice(arena, "        };\n");
    }

    const args_expr: []const u8 = if (request.args.items.len == 0) "null" else "&args";

    if (returns) |arg| {
        if (arg.interface) |named| {
            try out.print(arena,
                \\        const created = self.proxy().marshalConstructor({d}, {s}, &args) orelse
                \\            return error.ProxyCreationFailed;
                \\        return @ptrCast(created);
                \\    }}
                \\
            , .{ opcode, (try context.interfaceRef(named)).? });
        } else {
            try out.print(arena,
                \\        const created = self.proxy().marshalConstructorVersioned({d}, T.interface, version, &args) orelse
                \\            return error.ProxyCreationFailed;
                \\        return @ptrCast(created);
                \\    }}
                \\
            , .{opcode});
        }
    } else if (request.destructor) {
        try out.print(arena,
            \\        self.proxy().marshalDestructor({d}, {s});
            \\    }}
            \\
        , .{ opcode, args_expr });
    } else {
        try out.print(arena,
            \\        self.proxy().marshal({d}, {s});
            \\    }}
            \\
        , .{ opcode, args_expr });
    }
}

fn enumRef(arena: std.mem.Allocator, context: Context, reference: []const u8) ![]const u8 {
    if (std.mem.indexOfScalar(u8, reference, '.')) |dot| {
        const interface_name = reference[0..dot];
        const enum_name = try pascalCase(arena, reference[dot + 1 ..]);
        const target = (try context.typeRef(interface_name)) orelse return "u32";
        return std.fmt.allocPrint(arena, "{s}.{s}", .{ target, enum_name });
    }
    return pascalCase(arena, reference);
}
